services:
  apache-php84:
    build: ./docs/docker-files/production/
    # image : oberd/php-8.4-apache
    platform: linux/x86_64
    container_name: apache-php84-web
    ports:
      - 8081:80
      - 8443:443
    volumes:
      - ./src/web-app-2/src:/var/www/html
      # - ./src/cgi-data:/var/www/cgi-data
    # environment:
    #   - PHP_INCLUDE_PATH=/var/www/Your_CGI_DATA
    networks:
      - mynet-1
      
#   db-sever-pg17:
#     image: postgres:17
#     container_name: db-server-pg17
#     restart: unless-stopped
#     environment:
#       POSTGRES_USER: dbadmin
#       POSTGRES_PASSWORD: Abc123Abc123
#       POSTGRES_DB: php84_pg17_test
#     ports:
#       - "5433:5433"
#     volumes:
#       - pgdata:/var/lib/postgresql/data
#     networks:
#       - mynet-1
# volumes:
#   pgdata:
networks:
  mynet-1:
    external: true